#!/bin/bash
#PBS -l walltime=1:00:00,select=1:ncpus=1:mem=2gb
#PBS -J 1-8
#PBS -N cutadapt_gp_PCR
#PBS -M nicholas.mateyko@ubc.ca
#PBS -m abe
#PBS -A st-cdeboer-1
#PBS -o output_^array_index^.txt
#PBS -e error_^array_index^.txt
 
################################################################################
 
cd $PBS_O_WORKDIR
source /arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/miniconda3-4.6.14-f4hr756q34tvp7nsjn7hovq46fomaww6/etc/profile.d/conda.sh
conda activate cutadaptenv

set -e
logDir="log"
dataDir="/arc/project/st-cdeboer-1/nick/GibsonPrediction/data/untrimmed"
idx=$PBS_ARRAY_INDEX
mkdir -p log 

if [ ! -e $logDir/$idx.cutadapt.done ]
then
        cutadapt --untrimmed-o untrimmed1.$idx.fastq.gz --untrimmed-p untrimmed2.$idx.fastq.gz -m 30 --too-short-o too_short1.$idx.fastq.gz --too-short-p too_short2.$idx.fastq.gz \
        -M 30 --too-long-o too_long1.$idx.fastq.gz --too-long-p too_long2.$idx.fastq.gz -a ^CGCCAGCTCTTC...GAAGAGCCACTGGCCGTCGT -A ACGACGGCCAGTGGCTCTTC...GAAGAGCTGGCGAGATCGGA \
        -o GP_PCR_trimmed.$idx.r1.fastq.gz -p GP_PCR_trimmed.$idx.r2.fastq.gz $dataDir/GP_PCR_${idx}_read1.fastq.gz $dataDir/GP_PCR_${idx}_read2.fastq.gz
        
        touch $logDir/$idx.cutadapt.done
else
        echo Already performed cutadapt of $idx
fi
