data_dir: /arc/project/st-cdeboer-1/nick/GSC_seq_20240313

samples:
    linear_rep_1: TAGAGGCT-CGTGGAGT
    linear_rep_2: CGATGGTG-CACTACTT

adapters:
    up:
        a1: "atgaccatgattacgccaGCTCTTC...AGATCGGAAGAGC"
        a2: "GCTCTTCCGATCT...GAAGAGCtggcgtaatcatggtcat"
    down:
        a1: "GCTCTTCCGATCT...GAAGAGCcactggccgtcgttttac"
        a2: "gtaaaacgacggccagtgGCTCTTC...AGATCGGAAGAGC"
