data_dir: ../

samples:
    linear_rep1: linear_rep1

adapters:
    up:
        a1: "atgaccatgattacgccaGCTCTTC...AGATCGGAAGAGCACACGTCTGAAC"
        a2: "TCCCTACACGACGCTCTTCCGATCT...GAAGAGCtggcgtaatcatggtcat"
    down:
        a1: "GTTCAGACGTGTGCTCTTCCGATCT...GAAGAGCcactggccgtcgttttac"
        a2: "gtaaaacgacggccagtgGCTCTTC...AGATCGGAAGAGCGTCGTGTAGGGA"