samples:
    PCR_small_rep1_input: CTCACAAC-AGCTACCA_150bp.concat.fastq.gz
    PCR_large_rep1_input: TCTTCCTG-CGTTGGAA_150bp.concat.fastq.gz
    PCR_small_rep2_input: CCGTACAT-TTCAGTTG_150bp.concat.fastq.gz
    PCR_large_rep2_input: TACCTGGT-AGACCTCA_150bp.concat.fastq.gz
    PCR_small_rep1_assembled: AATGCCAA-ACGCACAA_150bp.concat.fastq.gz
    PCR_large_rep1_assembled: CTAGAACC-TTAGACCA_150bp.concat.fastq.gz
    PCR_small_rep2_assembled: ACTGGAAT-TTCACAGA_150bp.concat.fastq.gz
    PCR_large_rep2_assembled: AGCATAGT-CTCGACTG_150bp.concat.fastq.gz
    LIG_small_rep1_input: ACTATTGC-ACACAGGA_150bp.concat.fastq.gz
    LIG_large_rep1_input: TACGATTC-CTCTTCCG_150bp.concat.fastq.gz
    LIG_small_rep1_assembled: TGCAGTGG-AAGAAGCT_150bp.concat.fastq.gz
    LIG_large_rep1_assembled: TGCGAGGA-TAACCGTA_150bp.concat.fastq.gz
    LIG_small_rep2_input: ACGCCACA-TGGTTCGG_150bp.concat.fastq.gz
    LIG_large_rep2_input: CTTCGGTC-TAACGATG_150bp.concat.fastq.gz
    LIG_small_rep2_assembled: ACGGAGGT-AACTCTCG_150bp.concat.fastq.gz
    LIG_large_rep2_assembled: AGAATCAG-CTGTCGTA_150bp.concat.fastq.gz
    test_input: test_input
    test_assembled: test_assembled
